package hw3;

public enum CommandType {
    GET_AMOUNT,
    ADD_AMOUNT,
    TAKE_AMOUNT,
    ADD_PRODUCT_GROUP,
    ADD_PRODUCT_TO_GROUP,
    SET_PRICE,
    OK,
    REPEAT_COMMAND,
    END
//    CHECK_SERVER_CONNECTION,
//    CHECK_CLIENT_CONNECTION
}